#!/bin/bash -e
cd $(dirname $0)
tar xf xctf_missle.tar.gz
mkdir -p /home/missle
chown ctf:missle /home/missle/
chmod 770 /home/missle/
echo '' > /home/missle/flag
chown root:missle /home/missle/flag
chmod 740 /home/missle/flag
mkdir /home/missle/xctf_missle
cp -r xctf_missle/_rel /home/missle/xctf_missle/
touch /home/missle/missle.log
chown missle /home/missle/missle.log
chown -R ctf:ctf /home/missle/xctf_missle
rm -rf /home/missle/xctf_missle/_rel/xctf_missle_release/lib/xctf_missle-0.1.0/src/
systemctl start mysqld
ROOTPWD=$(pwgen 50 | head -n 1)
ADMINPWD=$(pwgen 50 | head -n 1)
ADMINPWDSHA=$(printf $ADMINPWD | sha1sum | awk '{print $1;}')
echo "
UPDATE mysql.user set password = password('$ROOTPWD');
create database missles;
create table missles.users (username text, password text);
insert into missles.users values('admin', '$ADMINPWDSHA');
create user 'missles'@'localhost';
grant select on missles.users to 'missles'@'localhost';
" > set.sql
echo $ROOTPWD $ADMINPWD > /root/xctf_missle_passwords
chmod 600 /root/xctf_missle_passwords
mysql -uroot < set.sql
systemctl restart mysqld
sudo -u ctf mkdir /home/missle/xctf_missle/_rel/xctf_missle_release/log
chown missle:missle /home/missle/xctf_missle/_rel/xctf_missle_release/log
sudo -u missle bash -c "cd /home/missle/xctf_missle; _rel/xctf_missle_release/bin/xctf_missle_release start"
sudo -u missle bash -c "cd /home/missle/xctf_missle; _rel/xctf_missle_release/bin/xctf_missle_release ping"
