#!/bin/bash -e
mkdir -p /home/missle
chown ctf:missle /home/missle/
chmod 770 /home/missle/
echo '' > /home/missle/flag
chown root:missle /home/missle/flag
chmod 740 /home/missle/flag
cp -r xctf_missle /home/missle/
chown -R ctf:ctf /home/missle/xctf_missle
sudo -u ctf bash -c "cd /home/missle/xctf_missle; make"
systemctl start mysqld
ROOTPWD=$(pwgen 50 | head -n 1)
ADMINPWD=$(pwgen 50 | head -n 1)
ADMINPWDSHA=$(echo $ADMINPWD | sha1sum | awk '{print $1;}')
echo "
UPDATE mysql.user set password = password('$ROOTPWD');
create database missles;
create table missles.users (username text, password text);
insert into missles.users values('admin', '$ADMINPWDSHA');
create user 'missles'@'localhost';
grant select on missles.users to 'missles'@'localhost';
" > set.sql
echo $ROOTPWD $ADMINPWD > passwords
mysql -uroot < set.sql
systemctl restart mysqld
sudo -u ctf mkdir /home/missle/xctf_missle/_rel/xctf_missle_release/log
chown missle:missle /home/missle/xctf_missle/_rel/xctf_missle_release/log
sudo -u missle bash -c "cd /home/missle/xctf_missle; _rel/xctf_missle_release/bin/xctf_missle_release start"
sudo -u missle bash -c "cd /home/missle/xctf_missle; _rel/xctf_missle_release/bin/xctf_missle_release ping"
